create table COMMENTS(
   ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   USER_ID BIGINT(20) NULL DEFAULT NULL,
   COMMENTS VARCHAR(500) NULL DEFAULT NULL,
   EXT_FLD VARCHAR(200) NULL DEFAULT NULL,
   CONTACT VARCHAR(100) NULL DEFAULT NULL,
   crt_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
)DEFAULT CHARSET=utf8;
